config/routes.rb
ConOnRails::Application.routes.draw do
  root controller: :events, action: :index, active: true

  concern :paginatable do
    get '(page/:page)', action: :index, on: :collection, as: ''
  end

  get '/public', to: 'sessions#new'
  get '/signout', to: 'sessions#destroy'
  get '/sessions/getroles', to: 'sessions#getroles'
  post '/sessions/set_index_filter', to: 'sessions#set_index_filter'
  post '/sessions/clear_index_filter', to: 'sessions#clear_index_filter'
  put '/sessions/set_pause_refresh', to: 'sessions#set_pause_refresh'
  get '/lost_and_found', to: 'lost_and_found#index'
  get '/admin', to: 'admin#index'
  get '/banner', to: 'application#banner'

  resources :admin, only: [:index]
  resources :audits, only: [:index]
  resources :contacts, except: [:destroy]
  resources :conventions, except: [:destroy]
  resources :departments

  resources :duty_board
  resources :duty_board_groups, except: [:show]

  resources :duty_board_slots do
    resources :duty_board_assignments
  end

  resources :events, except: [:destroy], concerns: :paginatable do
    collection do
      get 'export', format: :csv
      get 'review'
      get 'sticky'
      get 'secure'
      get 'tag/:tag', action: :tag
      post 'merge_events'
      get 'search_entries(/page/:page)', action: :search_entries, as: 'search_entries'
    end
  end

  resources :login_log, only: [:index]
  resources :lost_and_found, only: [:index]
  resources :lost_and_found_items, except: [:destroy] do
    collection do
      get :export, format: :csv
      get :searchform
    end
  end

  resources :radio_admin, only: [:index]
  resources :radio_assignments, only: %i[create update destroy]
  resources :radio_assignment_audits, only: [:index]
  resources :radio_groups do
    collection do
      get 'delindex'
    end
  end
  resources :radios do
    member do
      get 'checkout'
      get 'select_department'
    end
    collection do
      post 'search_volunteers' # This is cheating
    end
  end

  resources :roles
  resources :sessions, only: %i[new create destroy]
  resources :users do
    member do
      get :change_password
    end
  end

  resources :versions, only: [:index]
  resources :volunteers do
    post 'new_from_attendee'
    member do
      post 'associate'
      post 'new_user'
    end
    collection do
      get 'clear_all_radio_training'
    end
  end

  resources :vsps, except: %i[show destroy]

end

app/models/lost_and_found_item.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: lost_and_found_items
#
#  id              :integer          not null, primary key
#  category        :string
#  description     :string
#  details         :text
#  where_last_seen :string
#  where_found     :string
#  owner_name      :string
#  owner_contact   :text
#  created_at      :datetime
#  updated_at      :datetime
#  user_id         :integer
#  rolename        :string
#  who_claimed     :string
#

class LostAndFoundItem < ApplicationRecord
  has_paper_trail
  include LostAndFoundStateTags

  belongs_to :user

  RETIRED_CATEGORIES = {
    badge: 'Badges',
    costume_jewelry: 'Costume Jewelry',
    headgear: 'Headgear',
    keys: 'Keys',
    media: 'Media',
    money: 'Money/Cards/ID',
    paper: 'Paper (incl. Reg Packets)',
    phone: 'Phones',
    small_electronics: 'Small Electronics',
    wallet: 'Wallet',
    weapon: 'Weapons/Props'
  }.freeze

  VALID_CATEGORIES = {
    bag: 'Bags',
    bottle: 'Bottles',
    clothing: 'Clothing',
    electronics: 'Electronics',
    glasses: 'Glasses',
    headwear: 'Headwear',
    jewelry: 'Jewelry',
    lockbox: 'Lockbox (Money, ID, Cards, Wallets, Keys, Badges)',
    papers: 'Papers',
    prop: 'Props',
    toy: 'Toys',
    other_not_listed: 'Other Not Listed'
  }.freeze

  class << self
    def categories
      VALID_CATEGORIES
    end
  end

  validates :category, presence: true, allow_blank: false,
                       inclusion: { in: LostAndFoundItem.categories
                                                        .merge(RETIRED_CATEGORIES)
                                                        .values }
  validates :description, presence: true, allow_blank: false

  # These rules are a little complicated but it's worth it to ensure data integrity
  # 1] On create, only one of reported_missing or found can be true, and only the
  # correct fields should be defined
  # 2] It should always be true that certain fields are defined for certain flags
  # 3] These are hard to express using standard validators, but we always want
  # at least one of reported_missing or found to be true, and we want the "opposite"
  # where fields to be empty on create

  validates :where_last_seen, presence: true, allow_blank: false, if: :reported_missing?
  validates :owner_name, presence: true, allow_blank: false, if: :reported_missing?
  validates :where_found, presence: true, allow_blank: false, if: :found?

  validate :creation_state_correct, on: :create
  validate :always_missing_or_found
  validate :created_with_correct_descriptive_fields, on: :create

  def type
    return 'returned' if returned?
    return 'inventoried' if inventoried?
    return 'found' if found?
    return 'missing' if reported_missing?
  end

  def type_name
    type.capitalize
  end

  def always_missing_or_found
    return unless !reported_missing? && !found?

    errors.add :reported_missing, 'must be true if found is false'
    errors.add :found, 'must be true if reported_missing is false'
  end

  def created_with_correct_descriptive_fields
    # This used to enforce only one or the other, but once a missing item has been found,
    # we want both fields
    validate_where_found_empty if reported_missing? && !found?
    validate_where_last_seen_empty if found? && !reported_missing?
  end

  def creation_state_correct
    return unless found? && reported_missing?

    errors.add :reported_missing,
               'Item can be EITHER reported missing OR found on creation, but not both.'
  end

  def validate_where_last_seen_empty
    return if where_last_seen.blank?

    errors.add :where_last_seen, 'expected empty'
  end

  def validate_where_found_empty
    return if where_found.blank?

    errors.add :where_found, 'expected empty'
  end

  # rubocop:disable Metrics/MethodLength
  def self.to_csv(lfis)
    CSV.generate do |csv|
      csv << %w[ID Category Description Year]
      lfis.find_each do |lfi|
        csv << [
          lfi.id,
          lfi.category,
          lfi.description,
          lfi.created_at.year
        ].flatten
      end
    end
  end
  # rubocop:enable Metrics/MethodLength
end

app/controllers/lost_and_found_items_controller.rb
# frozen_string_literal: true

# rubocop:disable Metrics/ClassLength
class LostAndFoundItemsController < ApplicationController
  respond_to :html, :json

  before_action :categories, only: [:index]
  before_action :find_lfi, only: %i[show edit update]

  def index # rubocop:disable Metrics/MethodLength, Metrics/AbcSize
    return jump if lfi_search_params[:id].present?

    search_type = lfi_search_params[:search_type] || 'any'

    @title = 'Lost and Found Entries'

    @lfis = limit_by_convention policy_scope(LostAndFoundItem)
            .inventory(lfi_search_params[:inventory],
                       lfi_search_params[:exclude_inventoried])
            .page(lfi_search_params[:page]),
                                table: 'lost_and_found_items'
    if lfi_search_params[:keywords].present?
      @lfis = @lfis.where("(#{build_like('description', search_type)}) OR
                           (#{build_like('details', search_type)})")
    end
    @lfis = @lfis.where(category: @categories).references(:tags) if @categories.present?
    @lfis = lfi_search_params[:show_returned_only] ? @lfis.returned : @lfis.not_returned
    authorize @lfis
    @back_params = lfi_search_params
  end

  def show; end

  def new
    @lfi = LostAndFoundItem.new
    authorize @lfi

    @lfi.reported_missing = lfi_params[:reported_missing]
    @lfi.found            = lfi_params[:found]

    @title = "New #{@lfi.reported_missing ? 'Missing' : 'Found'} Item"
  end

  def edit
    @lfi.found = true if params[:found] == 'true'
    @lfi.returned = true if params[:returned] == 'true'
    @lfi.inventoried = true if params[:inventoried] == 'true'

    @title = "Edit #{@lfi.type_name} Item"
  end

  def create
    @lfi = LostAndFoundItem.new lfi_params
    authorize @lfi

    @lfi.user     = current_user
    @lfi.rolename = current_role_name

    if @lfi.save
      flash.now[:notice] =
        "TAG WITH #{@lfi.id} - #{@lfi.type_name} item was successfully created."
    end
    respond_with @lfi
  end

  def update
    @lfi.user     = current_user
    @lfi.rolename = current_role_name

    if @lfi.update lfi_params
      flash.now[:notice] =
        "#{@lfi.type_name} item was successfully updated."
    end
    respond_with @lfi, location: lost_and_found_item_path(@lfi, inventory: lfi_params[:inventory])
  end

  def searchform
    authorize :lost_and_found_item, :index?
  end

  def export
    respond_with do |f|
      @lfis = policy_scope(LostAndFoundItem).inventoried.order(:id)
      authorize @lfis, :index?
      f.csv do
        send_data LostAndFoundItem.to_csv(@lfis), filename: 'lost-and-found-inventory.csv',
                                                  type: 'text/csv'
      end
    end
  end

  protected

  def jump
    @lfi = policy_scope(LostAndFoundItem).find_by(id: params[:id])
    authorize @lfi
    if @lfi.present?
      return redirect_to lost_and_found_item_path(@lfi,
                                                  inventory: params[:inventory] || false)
    end

    render 'invalid'
  end

  def build_like(which, search_type)
    wrap_keywords_for_like.collect do |k|
      "#{which} ILIKE #{k}"
    end.join(search_type == 'all' ? ' AND ' : ' OR ')
  end

  def wrap_keywords_for_like
    params[:keywords].split.collect { |s| ActiveRecord::Base.connection.quote "%#{s}%" }
  end

  private

  def categories
    @categories ||= fix_old_categories(
      LostAndFoundItem.categories.collect do |k, v|
        next unless params.key? k.to_s

        v
      end.compact
    ).flatten
  end

  def find_lfi
    @lfi = LostAndFoundItem.find params[:id]
    authorize @lfi
  end

  def fix_old_categories(cats)
    @map ||= {
      'Badges' => %w[Badge Badges],
      'Bags' => %w[Bag Bags],
      'Bottles' => %w[Bottle Bottles],
      'Money/Cards/ID' => ['Money', 'Money/Cards/ID'],
      'Phones' => %w[Phone Phones],
      'Weapons/Props' => ['Weapon', 'Weapons/Props']
    }

    cats.collect { |c| @map[c] || c }
  end

  def lfi_search_params
    params.permit LostAndFoundItem.categories
                                  .keys + %i[id inventory keywords search_type
                                             reported_found inventoried exclude_inventoried returned
                                             reported_missing found page show_returned_only]
  end

  def lfi_params
    params.require(:lost_and_found_item)
          .permit :reported_missing, :category, :description, :where_last_seen,
                  :owner_name, :owner_contact, :where_found, :details, :found, :returned,
                  :who_claimed, :inventoried, :search_type
  end
end
# rubocop:enable Metrics/ClassLength

app/helpers/lost_and_found_items_helper.rb
# frozen_string_literal: true

module LostAndFoundItemsHelper
  def checkbox(tag, label, checked = false) # rubocop:disable Style/OptionalBooleanParameter
    check_box_tag(tag, '1', checked) + label_tag(tag, label.to_s)
  end
end

app/views/lost_and_found_items/_detail.html.erb
<div id="item">
  <h2><%= @lfi.type_name %> Item Details</h2>

  <div class="button">
    <%= link_to 'Edit Details', edit_lost_and_found_item_path(@lfi), class: 'btn btn-primary' %>
  </div>

  <div id="header">
    <div><strong>Item ID:</strong> <%= @lfi.id %> <strong>Category:</strong> <%= @lfi.category %></div>
    <div><strong>Last updated at</strong> <%= @lfi.updated_at %>
      <% if @lfi.user %>
          by <%= link_to @lfi.user.realname, @lfi.user %> as <%= @lfi.rolename %>
      <% end %>
    </div>
    <div><strong>Description:</strong> <%= @lfi.description %></div>
    <% if @lfi.reported_missing %>
        <div><strong>Where Last Seen:</strong> <%= @lfi.where_last_seen %></div>
        <div><strong>Owner Name:</strong> <%= @lfi.owner_name %></div>
        <div><strong>Owner Contact:</strong> <%= markdown @lfi.owner_contact %></div>
    <% end %>
    <% if @lfi.found %>
        <div><strong>Where Found:</strong> <%= @lfi.where_found %></div>
    <% end %>
    <% if @lfi.returned %>
        <div><strong>Claimed by:</strong> <%= @lfi.who_claimed %></div>
    <% end %>
  </div>
  <div><strong>Details:</strong></div>
  <div><%= markdown @lfi.details %></div>

  <div class="morf_button button">
    <% if !@lfi.returned %>
        <% if @lfi.reported_missing? and !@lfi.found? %>
            <%= link_to "Item Has Been Found", edit_lost_and_found_item_path(@lfi, found: true), class: 'item_found_button btn btn-default' %>
        <% end %>
        <%= link_to "Item Has Been Returned", edit_lost_and_found_item_path(@lfi, returned: true), class: 'item_returned_button btn btn-default' %>
        <% if params[:inventory] && !@lfi.inventoried? %>
            <%= link_to "Item Has Been Inventoried", edit_lost_and_found_item_path(@lfi, inventoried: true, inventory: params[:inventory]), class: 'item_inventoried_button btn btn-default' %>
        <% end %>
    <% end %>
  </div>
</div>

app/views/lost_and_found_items/_form.html.erb
<%= semantic_form_for @lfi, html: { class: "form-horizontal" } do |f| %>
    <%= f.inputs do %>
        <%= hidden_field_tag :inventory, params[:inventory] ? "1" : "0" %>
        <%= f.input :category, as: :select, collection: LostAndFoundItem.categories, class: background(@lfi) %>
        <%= f.input :description %>
        <% if @lfi.reported_missing? %>
            <%= f.input :reported_missing, as: :hidden, input_html: { value: true } %>
            <%= f.input :where_last_seen, label: "Where Last Seen" %>
            <%= f.input :owner_name, label: "Owner Name" %>
            <%= f.input :owner_contact, label: "Owner Contact" %>
        <% end %>
        <% if @lfi.found? || @lfi.returned? %>
            <%= f.input :found, as: :hidden, input_html: { value: true } %>
            <%= f.input :where_found, label: "Where Found" %>
        <% end %>
        <% if @lfi.returned? %>
            <%= f.input :returned, as: :hidden, input_html: { value: true } %>
            <%= f.input :who_claimed, label: "Claimed by" %>
        <% end %>
        <% if @lfi.inventoried? %>
            <%= f.input :inventoried, as: :hidden, input_html: { value: true } %>
        <% end %>
        <%= f.input :details, as: :text %>
    <% end %>
    <div><abbr text="required">*</abbr> denotes a required field</div>
    <%= f.actions do %>
        <%= f.action :submit, label: "Save" %>
    <% end %>
<% end %>

app/views/lost_and_found_items/_jump.html.slim
- content_for :search do
  .col-md-12
    .well.well-sm
      = form_tag :lost_and_found_items, method: :get, id: "lost_and_found_search_form", class: 'form-vertical' do
        .form-group
          = hidden_field_tag 'inventory', params[:inventory] || false
          = label_tag :id, 'Jump to an ID'
          = text_field_tag :id, nil, class: 'form-control'
        = submit_tag 'Submit', class: 'btn btn-success btn-sm'

      - if params[:inventory] == 'true'
        hr
        = form_tag :lost_and_found_items, method: :get, class: 'form-vertical' do
          .form-group
            = hidden_field_tag 'inventory', params[:inventory]
            = filter_by_convention
          .form-group
            label
              = check_box_tag :exclude_inventoried, 1, params[:exclude_inventoried]
              |  Exclude Inventoried
          = submit_tag "Filter", class: 'btn btn-primary btn-sm'
        hr
        = render 'mini_search_form'

app/views/lost_and_found_items/_mini_search_form.html.slim
= form_tag :lost_and_found_items, method: :get, id: 'lost_and_found_mini_form', class: 'form-vertical' do
  = hidden_field_tag :inventory, params[:inventory] ? '1' : '0'
  .form-group
    = filter_by_convention
  .form-group
    = label_tag :keywords
    = text_field_tag :keywords, '', class: 'form-control'
                                                                           git s

app/views/lost_and_found_items/edit.html.erb
<%= render partial: 'jump' %>

<div class="col-md-12">
  <h1>Edit <%= @lfi.type %> item </h1>

  <%= render "form" %>
</div>

<% content_for :side do %>
    <div class="col-md-12">
      <div class="well well-sm">
        <%= link_to 'Back', @lfi %>
      </div>
    </div>
<% end %>

app/views/lost_and_found_items/index.html.slim
= render partial: 'jump'

.col-md-12
  #paginator= paginate @lfis

  .table-responsive
    table.table.table-hover
      thead
        tr
          th ID
          th Category
          th Status
          th Description
      tbody
        - @lfis.each do |lfi|
            tr.clickable-row class="#{lfi.type}" data-href=lost_and_found_item_path(lfi, inventory: params[:inventory])
              td= lfi.id
              td= lfi.category
              td= lfi.type.upcase
              td= lfi.description
              noscript
                td= link_to 'View', lost_and_found_item_path(lfi, inventory: params[:inventory]), class: "btn btn-default item_#{lfi.type}_button"

  - newparams = { lost_and_found_item: {} }
  - if params[:reported_missing]
    - buttontype = "item_missing_button"
    - buttontext = "Create new missing item"
    - newparams[:lost_and_found_item][:reported_missing] = true
  - if params[:found]
    - buttontype = "item_found_button"
    - buttontext = "Create new found item"
    - newparams[:lost_and_found_item][:found] = true

  = link_to buttontext, new_lost_and_found_item_path(newparams), class: "#{buttontype} btn btn-default" if buttontext.present?

  #paginator= paginate @lfis

- content_for :side
  .col-md-12
    .well.well-sm
      div= link_to 'Back', searchform_lost_and_found_items_path(@back_params)
      - if current_user.modify_lost_and_found?
        div= link_to 'Open Inventory', lost_and_found_items_path(inventory: true)
        div= link_to 'Export Inventory', export_lost_and_found_items_path(format: :csv)

app/views/lost_and_found_items/invalid.html.slim
h2 Invalid ID
p The ID you tried to jump to does not exist!

- content_for :side do
  = link_to 'Back', request.referrer

app/views/lost_and_found_items/new.html.erb
<%= render partial: 'jump' %>

<div class="col-md-12">
  <h4>New <%= @lfi.type %> item </h4>
  <%= render partial: "form" %>
</div>

app/views/lost_and_found_items/searchform.html.slim
- @title = 'Lost and Found Search'
= render partial: 'jump'

.col-md-12
  h3 Search for an item
  = form_tag :lost_and_found_items, method: :get, id: "lost_and_found_search_form", class: 'form-horizontal' do
    = hidden_field_tag "reported_missing", params[:reported_missing] if params[:reported_missing]
    = hidden_field_tag "found", params[:found] if params[:found]
    .form-group
      .col-md-12.col-sm-12
        = filter_by_convention
    = field_set_tag "", id: "lost_and_found_checkboxes", class: 'form-horizontal' do
      .form-group
        - LostAndFoundItem.categories.each do |k, v|
          .col-md-6.col-sm-6
            = checkbox k, v, params[k]
        .col-md-6.col-sm-6
          = checkbox :show_returned_only, 'Returned Only'
    .form-group
      .col-md-4.col-sm-12
        = label_tag :keywords, "Search Keyword(s)"
      .col-md-8.col-sm-12
        = text_field_tag :keywords, params[:keywords], class: 'form-control'
    = field_set_tag "", id: "lost_and_found_search_options" do
      .form-group
        .col-md-4.col-sm-6
          = label_tag :search_type_all, "Find All"
          = radio_button_tag :search_type, "all", params[:search_type] == 'all'
        .col-md-4.col-sm-6
          = label_tag :search_type_any, "Find Any"
          = radio_button_tag :search_type, "any", params[:search_type].blank? || params[:search_type] == 'any'
    = submit_tag "Search", class: "btn btn-primary btn-lg"
  h4.alert-warning NOTE: This page does not and cannot create a new Lost and Found entry. You must search for an existing entry before you can create a new one.

- content_for :side do
  .col-md-12
    .well.well-sm
      div= link_to 'Back', lost_and_found_path
      - if current_user.modify_lost_and_found?
        div= link_to 'Open Inventory', lost_and_found_items_path(inventory: true)

app/views/lost_and_found_items/show.html.erb
<%= render partial: 'jump' %>
<div class="col-md-12">
  <%= render "detail" %>
</div>
<% content_for :side do %>
    <div class="col-md-12">
      <div class="well well-sm">
        <div><%= link_to 'Back', request.referrer %></div>
        <div><%= link_to 'Open Inventory', lost_and_found_items_path(inventory: true) %></div>
      </div>
    </div>
<% end %>