config/routes.rb
ConOnRails::Application.routes.draw do
  root controller: :events, action: :index, active: true

  concern :paginatable do
    get '(page/:page)', action: :index, on: :collection, as: ''
  end

  get '/public', to: 'sessions#new'
  get '/signout', to: 'sessions#destroy'
  get '/sessions/getroles', to: 'sessions#getroles'
  post '/sessions/set_index_filter', to: 'sessions#set_index_filter'
  post '/sessions/clear_index_filter', to: 'sessions#clear_index_filter'
  put '/sessions/set_pause_refresh', to: 'sessions#set_pause_refresh'
  get '/lost_and_found', to: 'lost_and_found#index'
  get '/admin', to: 'admin#index'
  get '/banner', to: 'application#banner'

  resources :admin, only: [:index]
  resources :audits, only: [:index]
  resources :contacts, except: [:destroy]
  resources :conventions, except: [:destroy]
  resources :departments

  resources :duty_board
  resources :duty_board_groups, except: [:show]

  resources :duty_board_slots do
    resources :duty_board_assignments
  end

  resources :events, except: [:destroy], concerns: :paginatable do
    collection do
      get 'export', format: :csv
      get 'review'
      get 'sticky'
      get 'secure'
      get 'tag/:tag', action: :tag
      post 'merge_events'
      get 'search_entries(/page/:page)', action: :search_entries, as: 'search_entries'
    end
  end

  resources :login_log, only: [:index]
  resources :lost_and_found, only: [:index]
  resources :lost_and_found_items, except: [:destroy] do
    collection do
      get :export, format: :csv
      get :searchform
    end
  end

  resources :radio_admin, only: [:index]
  resources :radio_assignments, only: %i[create update destroy]
  resources :radio_assignment_audits, only: [:index]
  resources :radio_groups do
    collection do
      get 'delindex'
    end
  end
  resources :radios do
    member do
      get 'checkout'
      get 'select_department'
    end
    collection do
      post 'search_volunteers' # This is cheating
    end
  end

  resources :roles
  resources :sessions, only: %i[new create destroy]
  resources :users do
    member do
      get :change_password
    end
  end

  resources :versions, only: [:index]
  resources :volunteers do
    post 'new_from_attendee'
    member do
      post 'associate'
      post 'new_user'
    end
    collection do
      get 'clear_all_radio_training'
    end
  end

  resources :vsps, except: %i[show destroy]

end

app/views/admin/index.html.erb
<ul>
  <!--li>Look up badge information (not yet implemented)</li-->
</ul>

<h1>Administration</h1>
<ul>
  <% if current_user and (current_user.can_admin_radios?) %>
      <li><%= link_to "Radios", radio_admin_index_url %></li>
  <% end %>
  <li><%= link_to "Contacts", contacts_url %></li>
  <% if current_user and current_user.can_admin_duty_board? %>
      <li><%= link_to "Duty Board Groups", duty_board_groups_path %></li>
      <li><%= link_to "Duty Board Slots", duty_board_slots_url %></li>
  <% end %>
  <li><%= link_to "Volunteers", volunteers_url %></li>
  <% if current_user and current_user.can_admin_users? %>
      <li><%= link_to "Users", users_url %></li>
      <li><%= link_to "Roles", roles_url %></li>
  <% end %>
  <% if current_user and current_user.can_read_audits? %>
      <li><%= link_to 'VSP list', vsps_path %></li>
    <% end %>
</ul>

<h1>System</h1>
<ul>
  <% if current_user and current_user.can_read_audits? %>
      <li><%= link_to 'Conventions (enables time-based filters)', conventions_url %></li>
      <li><%= link_to "(Pre-2014) View system log", audits_url %></li>
      <li><%= link_to "(2014-) View system log", versions_url %></li>
      <li><%= link_to "View login/out log", login_log_index_url %></li>
  <% end %>
  <li>Create backup (not yet implemented)</li>
</ul>	