config/routes.rb
ConOnRails::Application.routes.draw do
  root controller: :events, action: :index, active: true

  concern :paginatable do
    get '(page/:page)', action: :index, on: :collection, as: ''
  end

  get '/public', to: 'sessions#new'
  get '/signout', to: 'sessions#destroy'
  get '/sessions/getroles', to: 'sessions#getroles'
  post '/sessions/set_index_filter', to: 'sessions#set_index_filter'
  post '/sessions/clear_index_filter', to: 'sessions#clear_index_filter'
  put '/sessions/set_pause_refresh', to: 'sessions#set_pause_refresh'
  get '/lost_and_found', to: 'lost_and_found#index'
  get '/admin', to: 'admin#index'
  get '/banner', to: 'application#banner'

  resources :admin, only: [:index]
  resources :audits, only: [:index]
  resources :contacts, except: [:destroy]
  resources :conventions, except: [:destroy]
  resources :departments

  resources :duty_board
  resources :duty_board_groups, except: [:show]

  resources :duty_board_slots do
    resources :duty_board_assignments
  end

  resources :events, except: [:destroy], concerns: :paginatable do
    collection do
      get 'export', format: :csv
      get 'review'
      get 'sticky'
      get 'secure'
      get 'tag/:tag', action: :tag
      post 'merge_events'
      get 'search_entries(/page/:page)', action: :search_entries, as: 'search_entries'
    end
  end

  resources :login_log, only: [:index]
  resources :lost_and_found, only: [:index]
  resources :lost_and_found_items, except: [:destroy] do
    collection do
      get :export, format: :csv
      get :searchform
    end
  end

  resources :radio_admin, only: [:index]
  resources :radio_assignments, only: %i[create update destroy]
  resources :radio_assignment_audits, only: [:index]
  resources :radio_groups do
    collection do
      get 'delindex'
    end
  end
  resources :radios do
    member do
      get 'checkout'
      get 'select_department'
    end
    collection do
      post 'search_volunteers' # This is cheating
    end
  end

  resources :roles
  resources :sessions, only: %i[new create destroy]
  resources :users do
    member do
      get :change_password
    end
  end

  resources :versions, only: [:index]
  resources :volunteers do
    post 'new_from_attendee'
    member do
      post 'associate'
      post 'new_user'
    end
    collection do
      get 'clear_all_radio_training'
    end
  end

  resources :vsps, except: %i[show destroy]

end

app/models/radio_group.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: radio_groups
#
#  id         :integer          not null, primary key
#  name       :string
#  color      :string
#  notes      :text
#  created_at :datetime
#  updated_at :datetime
#

class RadioGroup < ApplicationRecord
  has_paper_trail

  COLORS = %w[blue red yellow green black].freeze

  #  audited
  has_many :radios, dependent: :destroy
  validates :name, presence: true, allow_blank: false
  validates :color, inclusion: { in: COLORS, message: 'Please select a color!' }

  def num_radios
    radios.count
  end
end

app/controllers/radio_groups_controller.rb
# frozen_string_literal: true

class RadioGroupsController < ApplicationController
  respond_to :html, :json

  before_action :find_radio_group, only: %i[show edit update destroy]

  def index(del_or_edit = 'edit')
    @radio_groups = policy_scope(RadioGroup).all
    authorize @radio_groups
    @del_or_edit = del_or_edit
  end

  def show; end

  # GET /radio_groups
  # GET /radio_groups.json
  def new
    @radio_group = RadioGroup.new
    authorize @radio_group
  end

  def delindex
    index('delete')
  end

  # GET /radio_groups/new
  # GET /radio_groups/new.json
  def edit; end

  # POST /radio_groups
  # POST /radio_groups.json
  def create
    @radio_group = RadioGroup.new radio_group_params
    authorize @radio_group
    flash.now[:notice] = 'Radio group was successfully created.' if @radio_group.save
    respond_with @radio_group
  end

  # PUT /radio_groups/1
  # PUT /radio_groups/1.json
  def update
    if @radio_group.update radio_group_params
      flash.now[:notice] =
        'Radio group was successfully updated.'
    end
    respond_with @radio_group
  end

  # DELETE /radio_groups/1
  # DELETE /radio_groups/1.json
  def destroy
    @radio_group.destroy
    respond_with @radio_group, location: radio_groups_path
  end

  protected

  def find_radio_group
    @radio_group = RadioGroup.find(params[:id])
    authorize @radio_group
  end

  def radio_group_params
    params.require(:radio_group).permit :name, :color, :notes
  end
end

app/helpers/radio_groups_helper.rb
# frozen_string_literal: true

module RadioGroupsHelper
end

app/views/radio_groups/_form.html.erb
<%= semantic_form_for @radio_group do |f| %>
    <%= f.inputs do %>
        <%= f.input :name %>
        <div id="selected-color"></div><%= f.input :color, as: :select, collection: RadioGroup::COLORS %>
        <%= f.input :notes %>
    <% end %>
    <script>
        $( function () { $( "#radio_group_name" ).addClass( "<%= @radio_group.color %>" ); })
        $( "#radio_group_color" ).change( function () {
            $( "#radio_group_name" ).removeClass( "blue red yellow green" );
            $( "#radio_group_name" ).addClass( $( "#radio_group_color option:selected" ).text() )
        } )
    </script>

    <%= f.actions do %>
        <%= f.action :submit %>
    <% end %>
<% end %>

app/views/radio_groups/edit.html.erb
<h1>Editing radio_group</h1>

<%= render 'form' %>

<%= link_to 'Show', @radio_group %> |
<%= link_to 'Back', radio_groups_path %>

app/views/radio_groups/index.html.erb
<h1>Choose a radio group to <%= @del_or_edit %></h1>
<table>
  <tr>
    <th>Name</th>
    <th>Notes</th>
    <th></th>
  </tr>

  <% @radio_groups.each do |radio_group| %>
      <tr>
        <td class="radio_group <%= radio_group.color %>"><%= link_to radio_group.name, radio_group %></td>
        <td class="radio_group_notes"><%= radio_group.notes %></td>
        <td>
          <% if @del_or_edit == "edit" %>
              <%= link_to 'Edit', edit_radio_group_path(radio_group) %>
          <% else %>
              <%= link_to 'Delete', radio_group, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
        </td>
      </tr>
  <% end %>
</table>

<br/>

<% content_for :side do %>
    <div><%= link_to 'Back', admin_path %></div>
    <div><%= link_to 'New Radio group', new_radio_group_path %></div>
    <% if @del_or_edit == "edit" %>
        <div><%= link_to 'Delete Radio group', delindex_radio_groups_path %></div>
    <% end %>
<% end %>

app/views/radio_groups/new.html.erb
<h1>New radio_group</h1>

<%= render 'form' %>

<% content_for :side do %>
<div><%= link_to 'Back', radio_groups_path %></div>
<% end %>

app/views/radio_groups/show.html.erb
<div class="radio_group_name <%= @radio_group.color %>">
  <%= @radio_group.name %>
</div>
<div class="label">Notes</div>
<div class="radio_group_notes"><%= @radio_group.notes %>
</div>

<% content_for :side do %>
    <div><%= link_to 'Back', radio_groups_path %></div>
    <div><%= link_to 'Create a radio group', new_radio_group_path %></div>
    <div><%= link_to 'Delete a radio group', delindex_radio_groups_path %></div>
    <div><%= link_to 'Edit', edit_radio_group_path(@radio_group) %></div>
<% end %>