config/routes.rb
ConOnRails::Application.routes.draw do
  root controller: :events, action: :index, active: true

  concern :paginatable do
    get '(page/:page)', action: :index, on: :collection, as: ''
  end

  get '/public', to: 'sessions#new'
  get '/signout', to: 'sessions#destroy'
  get '/sessions/getroles', to: 'sessions#getroles'
  post '/sessions/set_index_filter', to: 'sessions#set_index_filter'
  post '/sessions/clear_index_filter', to: 'sessions#clear_index_filter'
  put '/sessions/set_pause_refresh', to: 'sessions#set_pause_refresh'
  get '/lost_and_found', to: 'lost_and_found#index'
  get '/admin', to: 'admin#index'
  get '/banner', to: 'application#banner'

  resources :admin, only: [:index]
  resources :audits, only: [:index]
  resources :contacts, except: [:destroy]
  resources :conventions, except: [:destroy]
  resources :departments

  resources :duty_board
  resources :duty_board_groups, except: [:show]

  resources :duty_board_slots do
    resources :duty_board_assignments
  end

  resources :events, except: [:destroy], concerns: :paginatable do
    collection do
      get 'export', format: :csv
      get 'review'
      get 'sticky'
      get 'secure'
      get 'tag/:tag', action: :tag
      post 'merge_events'
      get 'search_entries(/page/:page)', action: :search_entries, as: 'search_entries'
    end
  end

  resources :login_log, only: [:index]
  resources :lost_and_found, only: [:index]
  resources :lost_and_found_items, except: [:destroy] do
    collection do
      get :export, format: :csv
      get :searchform
    end
  end

  resources :radio_admin, only: [:index]
  resources :radio_assignments, only: %i[create update destroy]
  resources :radio_assignment_audits, only: [:index]
  resources :radio_groups do
    collection do
      get 'delindex'
    end
  end
  resources :radios do
    member do
      get 'checkout'
      get 'select_department'
    end
    collection do
      post 'search_volunteers' # This is cheating
    end
  end

  resources :roles
  resources :sessions, only: %i[new create destroy]
  resources :users do
    member do
      get :change_password
    end
  end

  resources :versions, only: [:index]
  resources :volunteers do
    post 'new_from_attendee'
    member do
      post 'associate'
      post 'new_user'
    end
    collection do
      get 'clear_all_radio_training'
    end
  end

  resources :vsps, except: %i[show destroy]

end

app/models/radio.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: radios
#
#  id             :integer          not null, primary key
#  image_filename :string
#  notes          :string
#  number         :string
#  state          :string           default("in")
#  created_at     :datetime
#  updated_at     :datetime
#  radio_group_id :integer
#
# Indexes
#
#  index_radios_on_number  (number) UNIQUE
#

class Radio < ApplicationRecord
  has_paper_trail

  belongs_to :radio_group
  has_one :radio_assignment, dependent: :destroy

  validates :number, presence: true, uniqueness: true
  validates :radio_group, associated: true
  validates :state, presence: true, inclusion: { in: %w[in out retired] }

  scope :assigned, -> { where(state: 'out') }
  scope :unassigned, -> { where(state: 'in') }

  def name
    number
  end
end

app/controllers/radios_controller.rb
# frozen_string_literal: true

class RadiosController < ApplicationController
  respond_to :html, :json

  before_action :find_radio, only: %i[show edit update destroy checkout transfer select_department]
  before_action :find_radio_assignment, only: %i[select_department]
  before_action :find_radios, only: %i[index new create]

  def index; end
  def show; end

  def new
    @radio = Radio.new
    authorize @radio
  end

  # POST /radios/search_volunteers
  def search_volunteers # rubocop:disable Metrics/MethodLength
    @volunteers = Volunteer.radio_volunteer(params[:first_name],
                                            params[:last_name])
    authorize @volunteers

    respond_with do |format|
      format.html do
        if request.xhr?
          render partial: 'volunteers', locals: { radio: params[:radio] }
        else
          redirect_to root_path
        end
      end
    end
  end

  # GET /radios/1/select_department?volunteer=1
  def select_department # rubocop:disable Metrics/MethodLength
    respond_with do |format|
      format.html do
        if request.xhr?
          render partial: 'select_department', locals: { radio: params[:id],
                                                         radio_group: @radio.radio_group.id,
                                                         volunteer: params[:volunteer] }
        else
          redirect_to root_path
        end
      end
    end
  end

  # GET /radios/new
  # GET /radios/new.json
  def edit; end

  # GET /radios/1/checkout -- just gets the form
  def checkout
    @radio_assignment = RadioAssignment.new
    authorize @radio_assignment
  end

  def transfer
    @radio_assignment = @radio.radio_assignment
    authorize @radio_assignment
  end

  # POST /radios
  # POST /radios.json
  def create
    @radio = Radio.new radio_params
    flash.now[:notice] = 'Radio was successfully created.' if @radio.save
    respond_with @radio, location: radios_path
  end

  # PUT /radios/1
  # PUT /radios/1.json
  def update
    if params[:radio_assignment]
      @radio.radio_assignment = RadioAssignment.new params[:radio_assignment]
    end
    flash.now[:notice] = 'Radio was successfully updated.' if @radio.update radio_params
    respond_with @radio, location: radios_path
  end

  # DELETE /radios/1
  # DELETE /radios/1.json
  def destroy
    @radio.destroy
    respond_with @radio, location: radios_path
  end

  protected

  def find_radio
    @radio = Radio.find(params[:id])
    authorize @radio
  end

  def find_radio_assignment
    @radio_assignment = @radio.radio_assignment || RadioAssignment.new
    authorize @radio_assignment
  end

  def find_radios
    @q = policy_scope(Radio).ransack params[:q]
    @q.sorts = ['state desc', 'radios_number'] if @q.sorts.empty?
    @radios = @q.result(distinct: true).page(params[:page])
    authorize @radios
  end

  def radio_params
    params.require(:radio).permit :radio_group_id, :number, :state, :notes
  end
end

app/helpers/radios_helper.rb
# frozen_string_literal: true

module RadiosHelper
end

app/views/radios/_assigned.html.erb
<%= render partial: "radio", locals: { radio: assigned, edit: true } %>
<li><%= link_to assigned.radio_assignment.department.name, assigned.radio_assignment.department %></li>

app/views/radios/_form.html.erb
<%= simple_form_for @radio, wrapper: :inline_form, html: { class: 'form-inline' } do |f| %>
    <%= f.input :radio_group_id, as: :select, collection: RadioGroup.all, prompt: 'Select a group' %>
    <%= f.input :number, placeholder: 'Radio number e.g. 1234' %>
    <%= f.input :notes, placeholder: 'Notes' %>
    <%= f.button :submit, class: 'btn btn-success' %>
<% end %>

app/views/radios/_radio.html.slim
tr.clickable-row data-href=radio_url(radio)
  td class="#{radio.radio_group.color if radio.radio_group.present?}"= link_to(radio.radio_group.name, radio.radio_group) if radio.radio_group.present?
  td
    - if current_user and current_user.can_admin_radios?
      = link_to radio.number, edit_radio_path(radio)
    - else
      = radio.number
  td= radio.radio_assignment && radio.radio_assignment.department ? radio.radio_assignment.department.name : ""
  td= radio.radio_assignment && radio.radio_assignment.volunteer ? radio.radio_assignment.volunteer.first_name : ""
  td= radio.radio_assignment && radio.radio_assignment.volunteer ? radio.radio_assignment.volunteer.last_name : ""
  td= radio.state
  - if current_user and current_user.can_assign_radios?
    td
      - if radio.state == "in" and radio.radio_assignment.nil?
        = link_to "Check&nbsp;out".html_safe, checkout_radio_path(radio), method: :get, class: 'btn btn-xs btn-primary'
      - else
        = link_to "Transfer".html_safe, checkout_radio_path(radio), method: :get, class: 'btn btn-xs btn-warning'
        = link_to "Check&nbsp;in".html_safe, radio_assignment_path(radio.radio_assignment), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-xs btn-success'
      - if current_user && current_role.admin_radios?
          = link_to "Delete".html_safe, radio_path(radio), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-xs btn-danger'

app/views/radios/_radios.html.slim
#paginator= paginate @radios

.table-responsive
  table#radio-list.table.table-striped.table-hover
    thead
      tr
        th= sort_link @q, :radio_group_name, 'Group'
        th= sort_link @q, :number
        th= sort_link @q, :radio_assignment_volunteer_department_name, 'Department'
        th= sort_link @q, :radio_assignment_volunteer_volunteer_first_name, 'First Name'
        th= sort_link @q, :radio_assignment_volunteer_volunteer_last_name, 'Last Name'
        th= sort_link @q, :state
        th
    tbody
      = render partial: "radio", collection: @radios

#paginator= paginate @radios

app/views/radios/_search_form.html.slim
#search
  .col-md-12
    .well.well-sm
      = search_form_for @q, html: { class: 'form-vertical' } do |f|
        .form-group
          = f.label :number_matches, 'Radio Number'
          = f.text_field :number_matches, class: 'form-control form-control-sm'
        .form-group
          = f.label :radio_assignment_volunteer_first_name_cont, 'First name contains'
          = f.text_field :radio_assignment_volunteer_first_name_cont, class: 'form-control'
        .form-group
          = f.label :radio_assignment_volunteer_last_name_cont, 'Last name contains'
          = f.text_field :radio_assignment_volunteer_last_name_cont, class: 'form-control'
        = f.submit class: 'btn btn-sm btn-success'
          | Search

app/views/radios/_sidebar.html.slim
.col-md-12
  .well.well-sm
    div
      .glyphicon.glyphicon-signal
      | &nbsp;
      = link_to "Radios", radios_path
    div= link_to "Radio Groups", radio_groups_path
    div= link_to "Departments", departments_path

app/views/radios/_unassigned.html.erb
<%= render partial: "radio", locals: { radio: unassigned, edit: true } %>
<li class="radio_edit_button"><%= button_to "Assign", assign_radio_path(unassigned), method: :get %></li>

app/views/radios/_volunteers.html.slim
.table-responsive
  table.table
    tr
      th Name

    - @volunteers.each do |volunteer|
      tr
        td.radio_volunteer= volunteer.name
        td id="vol-#{volunteer.id}"= link_to 'Select', { action: :select_department, id: radio, volunteer: volunteer.id },
                                             method: :get, class: 'btn btn-sm', remote: true
        javascript:
          $( window.radios.bind_volunteer( "#{volunteer.id}", "#{volunteer.name}" ) );

app/views/radios/checkout.html.slim
h1 Check out radio

.table-responsive
  table.table#radio_summary
    thead
      tr
      th Radio Group
      th Radio Number
    tbody
      tr
        td class="radio_group #{@radio.radio_group.color}"= @radio.radio_group.name
        td.radio_number= @radio.name
        td.radio_volunteer#radio_volunteer

h2 First, find a volunteer

= form_tag({ action: :search_volunteers, controller: :radios }, id: 'volunteer_search', remote: true, class: 'form-inline') do
  = hidden_field_tag :radio, @radio.id
  = label_tag :first_name
  = text_field_tag :first_name
  = label_tag :last_name
  = text_field_tag :last_name
  = submit_tag "Find volunteer", class: 'btn btn-success'

#matching_volunteers
#errors

- content_for :side do
  = render partial: 'sidebar'

app/views/radios/edit.html.erb
<h1>Editing radio</h1>

<%= render 'form' %>

<% content_for :side do %>
<div><%= link_to 'Show', @radio %> </div>
<div><%= link_to 'Back', new_radio_path %></div>
<% end %>

app/views/radios/index.html.slim
.col-md-12
  h1 Listing radios

  - if current_user and current_user.can_admin_radios?
    = link_to 'New Radio', new_radio_path, class: 'btn btn-primary'

  = render 'radios', collection: @radios

  - if current_user and current_user.can_admin_radios?
    = link_to 'New Radio', new_radio_path, class: 'btn btn-primary'

  - content_for :side do
    = render partial: 'sidebar'

  - content_for :search do
    = render partial: 'search_form'

app/views/radios/new.html.erb
<h1>New radio</h1>

<div>
  <%= render 'form' %>
</div>

<%= render partial: 'radios' %>

<% content_for :side do %>
    <%= link_to 'Back', radios_path %>
<% end %>

app/views/radios/show.html.erb
<h1>Radio</h1>
<div>
  <span class="label">Radio Group:</span>
  <span class="radio_group <%= @radio.radio_group.color %>"><%= @radio.radio_group.name %></span>
</div>
<div>
  <span class="label">Number:</span>
  <span class="radio_number"><%= @radio.number %></span>
</div>
<div>
  <span class="label">Notes:</span>
  <span class="radio_notes"><%= @radio.notes %></span>
</div>

<% content_for :side do %>
    <div><%= link_to 'Edit', edit_radio_path(@radio) %></div>
    <div><%= link_to 'Delete', @radio, data: { confirm: 'Are you sure?' }, method: :delete %></div>
    <hr/>
    <%= render partial: 'sidebar' %>
<% end %>